### ISSUE TITLE
Make jwt more secure using refresh token and algorithm

### ISSUE THREAD

**Issue by sjathin** [kshitijyelpale/blockchain-hyperledger-fabric-electronic-patient-records#52]
Issue:
> As of now there is just a single token generated at all times

Solution:
> Improve and regenerated token for every 5minutes ?

**Comment by kshitijyelpale** [comment]
This issue is solved by the https://github.com/kshitijyelpale/blockchain-hyperledger-fabric-electronic-patient-records/pull/53
